import { CSSProperties } from 'react';

export const styles = (theme: 'light' | 'dark' = 'light') => ({
  scrollContainer: {
    flex: 1,
    backgroundColor: theme === 'light' ? '#FFFACD' : '#333',
    height: '100vh',
    overflowY: 'auto' as const,
  } as CSSProperties,
  scrollContent: {
    paddingBottom: '20px',
  } as CSSProperties,
  container: {
    padding: '15px',
  } as CSSProperties,
  header: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF4500' : '#FF69B4',
    textAlign: 'center' as const,
    marginTop: '10px',
    marginBottom: '10px',
    textShadow: `2px 2px 5px ${theme === 'light' ? '#FFD700' : '#FF00A0'}`,
  } as CSSProperties,
  subheader: {
    fontSize: '18px',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textAlign: 'center' as const,
    marginBottom: '10px',
    fontStyle: 'italic',
  } as CSSProperties,
  trustSection: {
    display: 'flex',
    justifyContent: 'space-around',
    marginTop: '10px',
    marginBottom: '10px',
  } as CSSProperties,
  trustText: {
    fontSize: '14px',
    color: theme === 'light' ? '#32CD32' : '#00FFFF',
    fontWeight: 'bold',
  } as CSSProperties,
  inputSection: {
    marginTop: '15px',
    marginBottom: '15px',
    backgroundColor: theme === 'light' ? '#F0E68C' : '#444',
    padding: '10px',
    borderRadius: '10px',
    border: `2px solid ${theme === 'light' ? '#FF69B4' : '#FF00A0'}`,
  } as CSSProperties,
  inputLabel: {
    fontSize: '18px',
    fontWeight: 'bold',
    textAlign: 'center' as const,
    padding: '5px',
    borderRadius: '5px',
    marginBottom: '5px',
  } as CSSProperties,
  picker: {
    height: '50px',
    width: '100%',
    border: `2px solid ${theme === 'light' ? '#ccc' : '#666'}`,
    borderRadius: '10px',
    marginBottom: '10px',
    padding: '8px',
    backgroundColor: theme === 'light' ? '#FFF' : '#555',
    color: theme === 'light' ? '#000' : '#FFF',
  } as CSSProperties,
  spinnerContainer: {
    alignItems: 'center',
    marginTop: '20px',
    marginBottom: '20px',
  } as CSSProperties,
  spinnerText: {
    fontSize: '16px',
  } as CSSProperties,
  buttonRow: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'space-around',
    marginTop: '10px',
    marginBottom: '10px',
  } as CSSProperties,
  errorContainer: {
    alignItems: 'center',
    marginTop: '10px',
    marginBottom: '10px',
  } as CSSProperties,
  error: {
    fontSize: '16px',
  } as CSSProperties,
  recipeCard: {
    backgroundColor: theme === 'light' ? '#FFF8DC' : '#444',
    padding: '20px',
    borderRadius: '15px',
    marginTop: '10px',
    marginBottom: '10px',
    border: `3px solid ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
    boxShadow: `0 4px 6px ${theme === 'light' ? '#FF69B4' : '#FFD700'}`,
  } as CSSProperties,
  recipeTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textAlign: 'center' as const,
    marginBottom: '10px',
    textShadow: `1px 1px 3px ${theme === 'light' ? '#FFD700' : '#FF00A0'}`,
  } as CSSProperties,
  recipeSectionContainer: {
    marginTop: '8px',
    marginBottom: '8px',
    padding: '10px',
    backgroundColor: theme === 'light' ? '#F0FFF0' : '#555',
    borderRadius: '10px',
    border: `2px solid ${theme === 'light' ? '#32CD32' : '#00FFFF'}`,
  } as CSSProperties,
  recipeSection: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF4500' : '#FF69B4',
    marginBottom: '5px',
  } as CSSProperties,
  recipeContent: {
    fontSize: '14px',
    color: theme === 'light' ? '#333' : '#FFF',
    marginLeft: '5px',
  } as CSSProperties,
  recipeItem: {
    fontSize: '14px',
    color: theme === 'light' ? '#4ECDC4' : '#00FFFF',
    marginLeft: '10px',
    marginTop: '3px',
  } as CSSProperties,
  recipeActions: {
    display: 'flex',
    flexWrap: 'wrap' as const,
    justifyContent: 'space-around',
    marginTop: '10px',
  } as CSSProperties,
  copyButton: {
    backgroundColor: theme === 'light' ? '#FF69B4' : '#FF00A0',
    padding: '10px',
    borderRadius: '5px',
    marginTop: '5px',
    marginBottom: '5px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    cursor: 'pointer',
  } as CSSProperties,
  copyButtonText: {
    color: theme === 'light' ? '#FFF' : '#FFF',
    textAlign: 'center' as const,
    fontWeight: 'bold',
  } as CSSProperties,
  favoriteItem: {
    fontSize: '16px',
    color: theme === 'light' ? '#FFD93D' : '#FFFF00',
    padding: '10px',
    borderBottom: `1px solid ${theme === 'light' ? '#ccc' : '#666'}`,
  } as CSSProperties,
  affiliateSection: {
    marginTop: '20px',
    marginBottom: '20px',
    padding: '15px',
    backgroundColor: theme === 'light' ? '#FF1493' : '#800080',
    borderRadius: '15px',
    border: `3px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    textAlign: 'center' as const,
  } as CSSProperties,
  affiliateHeader: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FFD700' : '#FFFF00',
    textAlign: 'center' as const,
    marginBottom: '10px',
    textShadow: `2px 2px 5px ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
  } as CSSProperties,
  affiliateButton: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: theme === 'light' ? '#32CD32' : '#00FF00',
    padding: '10px',
    borderRadius: '10px',
    marginTop: '5px',
    marginBottom: '5px',
    border: `2px solid ${theme === 'light' ? '#FF00A0' : '#FF69B4'}`,
    width: '100%',
    textDecoration: 'none',
  } as CSSProperties,
  affiliateImage: {
    width: '60px',
    height: '60px',
    marginRight: '10px',
    borderRadius: '5px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
  } as CSSProperties,
  affiliateText: {
    fontSize: '16px',
    color: theme === 'light' ? '#FFF' : '#FFF',
    fontWeight: 'bold',
    flexShrink: 1,
  } as CSSProperties,
  affiliateDisclaimer: {
    fontSize: '12px',
    color: theme === 'light' ? '#FFFF00' : '#FFD700',
    textAlign: 'center' as const,
    marginTop: '10px',
  } as CSSProperties,
  footer: {
    padding: '20px',
    marginTop: '20px',
    backgroundColor: theme === 'light' ? '#FFD700' : '#444',
    borderTop: `3px solid ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
  } as CSSProperties,
  footerContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    maxWidth: '800px',
    margin: '0 auto',
  } as CSSProperties,
  footerTextContainer: {
    textAlign: 'center' as const,
    flex: 1,
  } as CSSProperties,
  footerLogo: {
    width: '80px',
    height: '80px',
    border: `2px solid ${theme === 'light' ? '#FF00A0' : '#FF69B4'}`,
  } as CSSProperties,
  footerCopyright: {
    fontSize: '14px',
    color: theme === 'light' ? '#FF4500' : '#FF00A0',
    fontWeight: 'bold',
    margin: '10px 0',
  } as CSSProperties,
  footerLinks: {
    marginBottom: '10px',
  } as CSSProperties,
  footerPrivacyText: {
    fontSize: '16px',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textDecoration: 'underline',
    fontWeight: 'bold',
  } as CSSProperties,
  footerContactText: {
    fontSize: '12px',
    color: theme === 'light' ? '#FFF' : '#FFF',
    margin: '10px 0',
  } as CSSProperties,
  footerEmailLink: {
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textDecoration: 'underline',
  } as CSSProperties,
  footerFallback: {
    width: '80px',
    height: '80px',
    border: `2px solid ${theme === 'light' ? '#FF00A0' : '#FF69B4'}`,
  } as CSSProperties,
  modalOverlay: {
    position: 'fixed' as const,
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  } as CSSProperties,
  modalContent: {
    backgroundColor: theme === 'light' ? '#FFF8DC' : '#444',
    padding: '20px',
    borderRadius: '15px',
    textAlign: 'center' as const,
    border: `3px solid ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
    boxShadow: `0 4px 6px ${theme === 'light' ? '#FF69B4' : '#FFD700'}`,
    width: '80%',
    maxWidth: '400px',
  } as CSSProperties,
  modalImage: {
    width: '100px',
    height: '100px',
    marginBottom: '15px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    borderRadius: '10px',
  } as CSSProperties,
  modalText: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textAlign: 'center' as const,
    marginBottom: '10px',
  } as CSSProperties,
  modalSubText: {
    fontSize: '16px',
    color: theme === 'light' ? '#4ECDC4' : '#00FFFF',
    textAlign: 'center' as const,
    marginBottom: '20px',
  } as CSSProperties,
  modalButton: {
    backgroundColor: theme === 'light' ? '#FF9900' : '#FF4500',
    padding: '10px',
    borderRadius: '5px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    width: '50%',
    textAlign: 'center' as const,
    cursor: 'pointer',
  } as CSSProperties,
  modalButtonText: {
    color: theme === 'light' ? '#FFF' : '#FFF',
    fontWeight: 'bold',
    fontSize: '16px',
  } as CSSProperties,
  skeletonBox: {
    backgroundColor: theme === 'light' ? '#E0E0E0' : '#666',
    borderRadius: '4px',
    animation: 'pulse 1.5s infinite',
  } as CSSProperties,
  favorites: {
    marginTop: '10px',
    marginBottom: '10px',
    padding: '10px',
    backgroundColor: theme === 'light' ? '#FFF8DC' : '#444',
    borderRadius: '10px',
    border: `2px solid ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
  } as CSSProperties,
  subtitle: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    marginBottom: '10px',
    textAlign: 'center' as const,
  } as CSSProperties,
  searchRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '10px',
  } as CSSProperties,
  input: {
    backgroundColor: theme === 'light' ? '#FFF' : '#555',
    border: `1px solid ${theme === 'light' ? '#ccc' : '#666'}`,
    borderRadius: '5px',
    padding: '10px',
    fontSize: '16px',
    marginRight: '10px',
    flex: 1,
    color: theme === 'light' ? '#000' : '#FFF',
  } as CSSProperties,
  noFavorites: {
    fontSize: '16px',
    color: theme === 'light' ? '#FF4500' : '#FF00A0',
    textAlign: 'center' as const,
    marginTop: '10px',
  } as CSSProperties,
  favItemContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '5px',
  } as CSSProperties,
  favItem: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#000' : '#FFF',
  } as CSSProperties,
  removeButton: {
    backgroundColor: theme === 'light' ? '#FF3B30' : '#FF4500',
    paddingTop: '5px',
    paddingBottom: '5px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '5px',
    cursor: 'pointer',
  } as CSSProperties,
  removeButtonText: {
    color: theme === 'light' ? '#FFF' : '#FFF',
    fontSize: '14px',
  } as CSSProperties,
  clearButton: {
    backgroundColor: theme === 'light' ? '#FF3B30' : '#FF4500',
    padding: '10px',
    borderRadius: '5px',
    cursor: 'pointer',
  } as CSSProperties,
  clearButtonText: {
    color: theme === 'light' ? '#FFF' : '#FFF',
    fontSize: '14px',
  } as CSSProperties,
  chaosTooltip: {
    position: 'absolute' as const,
    backgroundColor: theme === 'light' ? '#FF00A0' : '#800080',
    color: '#FFF',
    padding: '5px 10px',
    borderRadius: '5px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    fontSize: '12px',
    zIndex: 10,
    animation: 'wobble 0.5s infinite',
  } as CSSProperties,
});