export const styles = (theme = 'light') => ({
  scrollContainer: {
    flex: 1,
    backgroundColor: theme === 'light' ? '#FFFACD' : '#333',
    height: '100vh',
    overflowY: 'auto',
  },
  scrollContent: {
    paddingBottom: '20px',
  },
  container: {
    padding: '15px',
  },
  header: {
    fontSize: '32px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF4500' : '#FF69B4',
    textAlign: 'center',
    marginTop: '10px',
    marginBottom: '10px',
    textShadow: `2px 2px 5px ${theme === 'light' ? '#FFD700' : '#FF00A0'}`,
  },
  subheader: {
    fontSize: '18px',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textAlign: 'center',
    marginBottom: '10px',
    fontStyle: 'italic',
  },
  trustSection: {
    display: 'flex',
    justifyContent: 'space-around',
    marginTop: '10px',
    marginBottom: '10px',
  },
  trustText: {
    fontSize: '14px',
    color: theme === 'light' ? '#32CD32' : '#00FFFF',
    fontWeight: 'bold',
  },
  inputSection: {
    marginTop: '15px',
    marginBottom: '15px',
    backgroundColor: theme === 'light' ? '#F0E68C' : '#444',
    padding: '10px',
    borderRadius: '10px',
    border: `2px solid ${theme === 'light' ? '#FF69B4' : '#FF00A0'}`,
  },
  inputLabel: {
    fontSize: '18px',
    fontWeight: 'bold',
    textAlign: 'center',
    padding: '5px',
    borderRadius: '5px',
    marginBottom: '5px',
  },
  picker: {
    height: '50px',
    width: '100%',
    border: `2px solid ${theme === 'light' ? '#ccc' : '#666'}`,
    borderRadius: '10px',
    marginBottom: '10px',
    padding: '8px',
    backgroundColor: theme === 'light' ? '#FFF' : '#555',
    color: theme === 'light' ? '#000' : '#FFF',
  },
  spinnerContainer: {
    alignItems: 'center',
    marginTop: '20px',
    marginBottom: '20px',
  },
  spinnerText: {
    fontSize: '16px',
  },
  buttonRow: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginTop: '10px',
    marginBottom: '10px',
  },
  errorContainer: {
    alignItems: 'center',
    marginTop: '10px',
    marginBottom: '10px',
  },
  error: {
    fontSize: '16px',
  },
  recipeCard: {
    backgroundColor: theme === 'light' ? '#FFF8DC' : '#444',
    padding: '20px',
    borderRadius: '15px',
    marginTop: '10px',
    marginBottom: '10px',
    border: `3px solid ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
    boxShadow: `0 4px 6px ${theme === 'light' ? '#FF69B4' : '#FFD700'}`,
  },
  recipeTitle: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textAlign: 'center',
    marginBottom: '10px',
    textShadow: `1px 1px 3px ${theme === 'light' ? '#FFD700' : '#FF00A0'}`,
  },
  recipeSectionContainer: {
    marginTop: '8px',
    marginBottom: '8px',
    padding: '10px',
    backgroundColor: theme === 'light' ? '#F0FFF0' : '#555',
    borderRadius: '10px',
    border: `2px solid ${theme === 'light' ? '#32CD32' : '#00FFFF'}`,
  },
  recipeSection: {
    fontSize: '18px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF4500' : '#FF69B4',
    marginBottom: '5px',
  },
  recipeContent: {
    fontSize: '14px',
    color: theme === 'light' ? '#333' : '#FFF',
    marginLeft: '5px',
  },
  recipeItem: {
    fontSize: '14px',
    color: theme === 'light' ? '#4ECDC4' : '#00FFFF',
    marginLeft: '10px',
    marginTop: '3px',
  },
  recipeActions: {
    display: 'flex',
    flexWrap: 'wrap',
    justifyContent: 'space-around',
    marginTop: '10px',
  },
  copyButton: {
    backgroundColor: theme === 'light' ? '#FF69B4' : '#FF00A0',
    padding: '10px',
    borderRadius: '5px',
    marginTop: '5px',
    marginBottom: '5px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    cursor: 'pointer',
  },
  copyButtonText: {
    color: theme === 'light' ? '#FFF' : '#FFF',
    textAlign: 'center',
    fontWeight: 'bold',
  },
  favoriteItem: {
    fontSize: '16px',
    color: theme === 'light' ? '#FFD93D' : '#FFFF00',
    padding: '10px',
    borderBottom: `1px solid ${theme === 'light' ? '#ccc' : '#666'}`,
  },
  affiliateSection: {
    marginTop: '20px',
    marginBottom: '20px',
    padding: '15px',
    backgroundColor: theme === 'light' ? '#FF1493' : '#800080',
    borderRadius: '15px',
    border: `3px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    textAlign: 'center',
  },
  affiliateHeader: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FFD700' : '#FFFF00',
    textAlign: 'center',
    marginBottom: '10px',
    textShadow: `2px 2px 5px ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
  },
  affiliateButton: {
    display: 'flex',
    alignItems: 'center',
    backgroundColor: theme === 'light' ? '#32CD32' : '#00FF00',
    padding: '10px',
    borderRadius: '10px',
    marginTop: '5px',
    marginBottom: '5px',
    border: `2px solid ${theme === 'light' ? '#FF00A0' : '#FF69B4'}`,
    width: '100%',
    textDecoration: 'none',
  },
  affiliateImage: {
    width: '60px',
    height: '60px',
    marginRight: '10px',
    borderRadius: '5px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
  },
  affiliateText: {
    fontSize: '16px',
    color: theme === 'light' ? '#FFF' : '#FFF',
    fontWeight: 'bold',
    flexShrink: 1,
  },
  affiliateDisclaimer: {
    fontSize: '12px',
    color: theme === 'light' ? '#FFFF00' : '#FFD700',
    textAlign: 'center',
    marginTop: '10px',
  },
  footer: {
    padding: '20px',
    marginTop: '20px',
    backgroundColor: theme === 'light' ? '#FFD700' : '#444',
    borderTop: `3px solid ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
  },
  footerContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    maxWidth: '800px',
    margin: '0 auto',
  },
  footerTextContainer: {
    textAlign: 'center',
    flex: 1,
  },
  footerLogo: {
    width: '80px',
    height: '80px',
    border: `2px solid ${theme === 'light' ? '#FF00A0' : '#FF69B4'}`,
  },
  footerCopyright: {
    fontSize: '14px',
    color: theme === 'light' ? '#FF4500' : '#FF00A0',
    fontWeight: 'bold',
    margin: '10px 0',
  },
  footerLinks: {
    marginBottom: '10px',
  },
  footerPrivacyText: {
    fontSize: '16px',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textDecoration: 'underline',
    fontWeight: 'bold',
  },
  footerContactText: {
    fontSize: '12px',
    color: theme === 'light' ? '#FFF' : '#FFF',
    margin: '10px 0',
  },
  footerEmailLink: {
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textDecoration: 'underline',
  },
  footerFallback: {
    width: '80px',
    height: '80px',
    border: `2px solid ${theme === 'light' ? '#FF00A0' : '#FF69B4'}`,
  },
  modalOverlay: {
    position: 'fixed',
    top: 0,
    left: 0,
    right: 0,
    bottom: 0,
    backgroundColor: 'rgba(0, 0, 0, 0.5)',
    display: 'flex',
    justifyContent: 'center',
    alignItems: 'center',
    zIndex: 1000,
  },
  modalContent: {
    backgroundColor: theme === 'light' ? '#FFF8DC' : '#444',
    padding: '20px',
    borderRadius: '15px',
    textAlign: 'center',
    border: `3px solid ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
    boxShadow: `0 4px 6px ${theme === 'light' ? '#FF69B4' : '#FFD700'}`,
    width: '80%',
    maxWidth: '400px',
  },
  modalImage: {
    width: '100px',
    height: '100px',
    marginBottom: '15px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    borderRadius: '10px',
  },
  modalText: {
    fontSize: '24px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    textAlign: 'center',
    marginBottom: '10px',
  },
  modalSubText: {
    fontSize: '16px',
    color: theme === 'light' ? '#4ECDC4' : '#00FFFF',
    textAlign: 'center',
    marginBottom: '20px',
  },
  modalButton: {
    backgroundColor: theme === 'light' ? '#FF9900' : '#FF4500',
    padding: '10px',
    borderRadius: '5px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    width: '50%',
    textAlign: 'center',
    cursor: 'pointer',
  },
  modalButtonText: {
    color: theme === 'light' ? '#FFF' : '#FFF',
    fontWeight: 'bold',
    fontSize: '16px',
  },
  skeletonBox: {
    backgroundColor: theme === 'light' ? '#E0E0E0' : '#666',
    borderRadius: '4px',
    animation: 'pulse 1.5s infinite',
  },
  favorites: {
    marginTop: '10px',
    marginBottom: '10px',
    padding: '10px',
    backgroundColor: theme === 'light' ? '#FFF8DC' : '#444',
    borderRadius: '10px',
    border: `2px solid ${theme === 'light' ? '#FF4500' : '#FF00A0'}`,
  },
  subtitle: {
    fontSize: '22px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#FF00A0' : '#FFD700',
    marginBottom: '10px',
    textAlign: 'center',
  },
  searchRow: {
    display: 'flex',
    alignItems: 'center',
    marginBottom: '10px',
  },
  input: {
    backgroundColor: theme === 'light' ? '#FFF' : '#555',
    border: `1px solid ${theme === 'light' ? '#ccc' : '#666'}`,
    borderRadius: '5px',
    padding: '10px',
    fontSize: '16px',
    marginRight: '10px',
    flex: 1,
    color: theme === 'light' ? '#000' : '#FFF',
  },
  noFavorites: {
    fontSize: '16px',
    color: theme === 'light' ? '#FF4500' : '#FF00A0',
    textAlign: 'center',
    marginTop: '10px',
  },
  favItemContainer: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '5px',
  },
  favItem: {
    fontSize: '20px',
    fontWeight: 'bold',
    color: theme === 'light' ? '#000' : '#FFF',
  },
  removeButton: {
    backgroundColor: theme === 'light' ? '#FF3B30' : '#FF4500',
    paddingTop: '5px',
    paddingBottom: '5px',
    paddingLeft: '10px',
    paddingRight: '10px',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  removeButtonText: {
    color: theme === 'light' ? '#FFF' : '#FFF',
    fontSize: '14px',
  },
  clearButton: {
    backgroundColor: theme === 'light' ? '#FF3B30' : '#FF4500',
    padding: '10px',
    borderRadius: '5px',
    cursor: 'pointer',
  },
  clearButtonText: {
    color: theme === 'light' ? '#FFF' : '#FFF',
    fontSize: '14px',
  },
  chaosTooltip: {
    position: 'absolute',
    backgroundColor: theme === 'light' ? '#FF00A0' : '#800080',
    color: '#FFF',
    padding: '5px 10px',
    borderRadius: '5px',
    border: `2px solid ${theme === 'light' ? '#FFD700' : '#FFFF00'}`,
    fontSize: '12px',
    zIndex: 10,
    animation: 'wobble 0.5s infinite',
  },
});